name: CI

on: [push]

jobs:
  test:
    name: Rus Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Test
      shell: pwsh
      run: ./build.ps1 -Task Test -Bootstrap
